version: '3'
services:
   payumba:
    build: .
    networks:
      - default
    ports:
      - "8000:8000"
    volumes:
      - .:/umbapay
    command: python manage.py migrate
    command: python manage.py runserver 0.0.0.0:8000